# Generated by Django 3.2 on 2023-07-23 18:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20230722_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveConstraint(
            model_name='favourite',
            name='unique_favourite',
        ),
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='unique_ingredients_in_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_author_name',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_shoppingcart',
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tags',
        ),
        migrations.RemoveConstraint(
            model_name='taginrecipe',
            name='unique_tagrecipe',
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и публикации рецепта'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#006400', help_text='Введите цвет тега. Например, #006400', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Введите значение цвета в формате HEX!', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название тега'),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('recipe', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='ingredientinrecipe',
            unique_together={('recipe', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('recipe', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='taginrecipe',
            unique_together={('recipe', 'tag')},
        ),
    ]
