# Generated by Django 3.2 on 2023-07-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230723_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipes/%y_%m_%d', verbose_name='Изображение рецепта'),
        ),
    ]
